apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-hc-deploy
  labels:
    app: healthcare-hc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-hc-app
  template:
    metadata:
      labels:
        app: healthcare-hc-app
    spec:
      containers:
      - name: healthcare-hc-container
        image: sanjeev7779/healthcare-hc-app
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-hc-np-service
  labels:
    app: healthcare-hc-app
spec:
  selector:
    app: healthcare-hc-app

  type: NodePort
  ports:
  - nodePort: 31033   
    port: 8082
    targetPort: 8082